/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard, Andrew Yang, Matthew Jasper
-/
import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Local -- abstract Hecke ops
import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Abstract -- abstract Hecke ops
import FLT.AutomorphicForm.QuaternionAlgebra.Defs -- definitions of automorphic forms
import FLT.QuaternionAlgebra.NumberField -- rigidifications of quat algs
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.RingTheory.DedekindDomain.FiniteAdeleRing
import FLT.DedekindDomain.FiniteAdeleRing.LocalUnits -- for (π 0; 0 1)
import FLT.Mathlib.Topology.Algebra.RestrictedProduct.TopologicalSpace
import FLT.Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
/-

# Concrete Hecke operators

Hecke operators for spaces of automorphic forms on totally definite quaternion algebras
of level `U₁(S)`, where `S` is a finite set of finite places of the totally real number
field `F`, and `U₁(S)` is the matrices which are of the form `(a *;0 a)` mod `v` for
all `v ∈ S`.

## Main definitions

All in the `TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm` namespace.

Let `r : Rigidification F D` be an `𝔸_F^∞`-algebra isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`,
needed to interpret the local factors `Dᵥ` as matrix rings so we can define Hecke operators
as matrices.

* `HeckeOperator.T r R v` -- the Hecke operator `Tᵥ` associated to `(ϖᵥ 0; 0 1)` at a (good)
  place `v` (via the rigidification `r`), as an `R`-linear endomorphism of
  `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeOperator.U r S R a ha` -- the Hecke operator `Uᵥ,ₐ` associated to `(a 0;0 1)` at
  a (bad) place `v`; here `a : v.adicCompletionIntegers F` and `ha` is a proof that `a ≠ 0`,
  as an `R`-linear endomorphism of `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeAlgebra F D r S R` -- the Hecke algebra generated by the `Tᵥ` and `Uᵥ,ₐ`. Built
  as a type, coerced from a subalgebra of the endomorphism algebra of the forms.
* `HeckeAlgebra.T D r R v hv` -- `Tᵥ` as a term of type `HeckeAlgebra F D r S R`
* `HeckeAlgebra.U D r R v hv a ha` -- `Uᵥ,ₐ` as a term of type `HeckeAlgebra F D r S R`

-/

/-

## A finiteness result

The existence of abstract Hecke operators relies on a certain double coset space being
a finite union of single cosets. In our situation we can supply this finiteness proof
via a topological argument, which we abstract here.

-/

section finiteness

open Topology Set

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {g : G} {U V : Subgroup G}

open scoped Pointwise in
lemma QuotientGroup.mk_image_finite_of_compact_of_open
    (hU : IsCompact (U : Set G)) (hVopen : IsOpen (V : Set G)) :
    (QuotientGroup.mk '' (U * {g}) : Set (G ⧸ V)).Finite := by
  have : DiscreteTopology (G ⧸ V) := by
    rw [discreteTopology_iff_forall_isOpen]
    intro s
    rw [← (isQuotientMap_mk V).isOpen_preimage, ← (QuotientGroup.mk_surjective).image_preimage s,
      preimage_image_mk_eq_iUnion_image, iUnion_subtype]
    conv in ⋃ x ∈ _, _ => change ⋃ x ∈ (V : Set G), _
    rw [iUnion_mul_right_image]
    exact IsOpen.mul_left hVopen
  exact ((hU.mul <| isCompact_singleton).image continuous_mk).finite_of_discrete

end finiteness


open NumberField IsQuaternionAlgebra.NumberField IsDedekindDomain

-- let F be a totally real number field
variable (F : Type*) [Field F] [NumberField F] [IsTotallyReal F]

-- Let D/F be a quaternion algebra
variable (D : Type*) [Ring D] [Algebra F D] [IsQuaternionAlgebra F D]

-- Let r be a rigidification of D, which is a collection of isomorphisms D ⊗ Fᵥ = M₂(Fᵥ)
-- for all finite places v of F, compatible with the adelic structure (i.e. inducing
-- an isomorphism D ⊗_F 𝔸_F^f = M₂(𝔸_F^f))
variable (r : Rigidification F D)

-- Let S be a finite set of finite plaes of F (the level)
variable (S : Finset (HeightOneSpectrum (𝓞 F)))

-- let P be a good prime
variable {P : HeightOneSpectrum (𝓞 F)} (hP : P ∉ S)

open TotallyDefiniteQuaternionAlgebra
-- let's define T_P : S_2^D(U_1(S)) -> S_2^D(U_1(S))
namespace TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm

open IsDedekindDomain.HeightOneSpectrum

open scoped TensorProduct

-- Oops! This is also `IsDedekindDomain.HeightOneSpectrum.QuaternionAlgebra.TameLevel`
-- in `FLT.QuaternionAlgebra.NumberField`, defined differently (using `Subgroup.comap` not `map`).
-- Don't care which one survives.
variable {F D} in
open scoped TensorProduct.RightActions in
/-- U1(S) -/
noncomputable abbrev U1 : Subgroup (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
  Subgroup.map (Units.map r.symm.toMonoidHom) (GL2.TameLevel S)

omit [IsTotallyReal F] in
variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_compact :
    IsCompact (U1 r S :
      Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) := by
  rw [U1, Subgroup.coe_map]
  have hc : Continuous r.symm :=
    IsDedekindDomain.HeightOneSpectrum.Rigidification.continuous_invFun D r
  exact (GL2.TameLevel.isCompact S).image
    (Continuous.units_map r.symm.toMonoidHom hc)

omit [IsTotallyReal F] in
variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_open :
    IsOpen (U1 r S :
      Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) := by
  rw [U1, Subgroup.coe_map]
  have hcr : Continuous r :=
    IsDedekindDomain.HeightOneSpectrum.Rigidification.continuous_toFun D r
  rw [Set.image_eq_preimage_of_inverse
    (f := Units.map r.symm.toMonoidHom)
    (g := Units.map r.toMonoidHom)
    (fun x => by ext; simp) (fun x => by ext; simp)]
  exact (GL2.TameLevel.isOpen S).preimage
    (Continuous.units_map r.toMonoidHom hcr)

variable (R : Type*) [CommRing R]

namespace HeckeOperator

variable {F D S} in
set_option maxSynthPendingDepth 1 in
open scoped TensorProduct.RightActions in
/-- The Hecke operator T_v as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S).
-/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  letI : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _
  let g : (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
    Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
    ![FiniteAdeleRing.localUniformiserUnit F v, 1])
  AbstractHeckeOperator.HeckeOperator (R := R) g (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_open r S))

section U

variable {F D}

variable {v : HeightOneSpectrum (𝓞 F)} (α : v.adicCompletionIntegers F) (hα : α ≠ 0)

open scoped TensorProduct.RightActions
open scoped Pointwise

noncomputable instance : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _

/-- The (global) matrix element `diag[α, 1]`. -/
noncomputable abbrev diag :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _ (Local.GL2.diag α hα)))

/-- The (global) matrix element `(unipotent t) * (diag α hα) = !![α, t; 0, 1]`.
Here `t ∈ 𝒪ᵥ / α` and we lift it arbitrarily to `𝒪ᵥ`. -/
noncomputable def unipotent_mul_diag (t : ↑(adicCompletionIntegers F v) ⧸ (Ideal.span {α})) :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _
      (Local.GL2.unipotent_mul_diag α hα (Quotient.out t : adicCompletionIntegers F v))))

/-- The set of elements `unipotent_mul_diag`, that is, the elements of `(D ⊗ 𝔸_F^∞)ˣ`
which are `(α t;0 1)` at `v` and the identity elsewhere, as `t` runs through a set
of coset reps of `𝓞ᵥ / α`. These will form a set of coset representatives for `U1 diag U1`.
-/
noncomputable def unipotent_mul_diag_image :
    Set (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  (unipotent_mul_diag r α hα) '' ⊤

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
lemma unipotent_mul_diag_inj :
    Set.InjOn (unipotent_mul_diag r α hα) ⊤ := by
  intro t₁ h₁ t₂ h₂ h
  simp only [unipotent_mul_diag, EmbeddingLike.apply_eq_iff_eq, RestrictedProduct.ext_iff] at h
  let h' := h v; simp only [RestrictedProduct.mulSingle_eq_same, Units.ext_iff] at h'
  rw [← Matrix.ext_iff] at h'
  let h'' := h' 0 1
  simpa [Local.GL2.unipotent_mul_diag, Matrix.GeneralLinearGroup.GL2.unipotent, Local.GL2.diag,
    Matrix.unitOfDetInvertible, Matrix.GeneralLinearGroup.diagonal] using h''

/-- The double coset space `U₁(S) diag(αᵥ,1) U₁(S)` as a set of left cosets. -/
noncomputable def U1diagU1 :
    Set ((D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ ⧸ (U1 r S)) :=
  QuotientGroup.mk '' ((U1 r S) * {diag r α hα})

set_option maxHeartbeats 800000 in
-- Increased heartbeat due to significant `rfl`/definitional unfolding through the
-- restricted-product + rigidification pipeline in the InjOn and SurjOn branches.
omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
theorem bijOn_unipotent_mul_diagU1_U1diagU1 (hv : v ∈ S) :
    (unipotent_mul_diag_image r α hα).BijOn QuotientGroup.mk (U1diagU1 r S α hα) := by
  refine ⟨?_, ?_, ?_⟩
  · -- MapsTo: each `unipotent_mul_diag r α hα i` can be written as `u_glob * diag r α hα`
    -- for some `u_glob ∈ U1 r S`, where `u_glob` is the image of a v-supported unipotent
    -- matrix `!![1, (out i); 0, 1]` through the restricted product + rigidification.
    rintro _ ⟨i, _, rfl⟩
    -- Define the v-supported global unipotent element.
    set u_glob : (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
      Units.mapEquiv r.symm.toMulEquiv
        (FiniteAdeleRing.GL2.restrictedProduct.symm
          (RestrictedProduct.mulSingle _ v
            (Matrix.GeneralLinearGroup.GL2.unipotent
              ((Quotient.out i : adicCompletionIntegers F v) :
                adicCompletion F v)))) with hu_glob_def
    -- Show `u_glob ∈ U1 r S`.
    have hu_glob_mem : u_glob ∈ U1 r S := by
      refine Subgroup.mem_map.mpr ⟨_, ?_, rfl⟩
      refine ⟨fun w => ?_, fun w _ => ?_⟩
      · by_cases hwv : w = v
        · subst hwv
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact (Local.GL2.unipotent_mem_U1 (v := w) (Quotient.out i)).1
        · rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localFullLevel w).one_mem
      · by_cases hwv : w = v
        · subst hwv
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact Local.GL2.unipotent_mem_U1 (v := w) (Quotient.out i)
        · rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localTameLevel w).one_mem
    -- Show `unipotent_mul_diag r α hα i = u_glob * diag r α hα`.
    have h_eq : unipotent_mul_diag r α hα i = u_glob * diag r α hα := by
      rw [hu_glob_def]
      unfold unipotent_mul_diag diag
      rw [← map_mul, ← map_mul, ← RestrictedProduct.mulSingle_mul]
      rfl
    refine ⟨u_glob * diag r α hα, Set.mul_mem_mul hu_glob_mem rfl, ?_⟩
    rw [← h_eq]
  · -- InjOn: if `mk (unipotent_mul_diag i) = mk (unipotent_mul_diag j)`, then the ratio
    -- is in `U1 r S`, and its projection at `v` is a unipotent `!![1, (j - i)/α; 0, 1]`.
    -- For this to be in `localFullLevel v` we need `(j - i)/α ∈ O_v`, i.e. `α | (j - i)`,
    -- i.e. `i = j` in `O_v / α`.
    rintro _ ⟨i, _, rfl⟩ _ ⟨j, _, rfl⟩ h
    refine congrArg (unipotent_mul_diag r α hα) ?_
    have hratio : (unipotent_mul_diag r α hα i)⁻¹ * (unipotent_mul_diag r α hα j) ∈ U1 r S :=
      QuotientGroup.eq.mp h
    set t_i : adicCompletionIntegers F v := Quotient.out i
    set t_j : adicCompletionIntegers F v := Quotient.out j
    -- Directly build a witness `w' ∈ GL2.TameLevel S`, then derive that its image at `v`
    -- (which is `(Local.unipotent_mul_diag t_i)⁻¹ * Local.unipotent_mul_diag t_j
    --  = Local.unipotent (α⁻¹ * (t_j - t_i))`) lies in `localFullLevel v`.
    set g_loc : GL (Fin 2) (adicCompletion F v) :=
      (Local.GL2.unipotent_mul_diag α hα t_i)⁻¹ *
        Local.GL2.unipotent_mul_diag α hα t_j with hg_loc_def
    set w' : GL (Fin 2) (FiniteAdeleRing (𝓞 F) F) :=
      FiniteAdeleRing.GL2.restrictedProduct.symm
        (RestrictedProduct.mulSingle _ v g_loc) with hw'_def
    -- The image of `w'` under `Units.mapEquiv r.symm.toMulEquiv` is the ratio.
    have h_image : Units.mapEquiv r.symm.toMulEquiv w' =
        (unipotent_mul_diag r α hα i)⁻¹ * (unipotent_mul_diag r α hα j) := by
      change Units.mapEquiv r.symm.toMulEquiv
          (FiniteAdeleRing.GL2.restrictedProduct.symm
            (RestrictedProduct.mulSingle _ v g_loc)) =
        (unipotent_mul_diag r α hα i)⁻¹ * (unipotent_mul_diag r α hα j)
      unfold unipotent_mul_diag
      rw [← map_inv, ← map_mul, ← map_inv, ← map_mul, ← RestrictedProduct.mulSingle_inv,
        ← RestrictedProduct.mulSingle_mul]
    -- Extract the preimage from membership in U1.
    obtain ⟨w, hw_mem, hw_eq⟩ := Subgroup.mem_map.mp hratio
    -- Since `Units.mapEquiv r.symm.toMulEquiv` is injective and both `w` and `w'` map to
    -- the ratio, we have `w = w'`.
    have hw'_eq : w' = w := by
      apply (Units.mapEquiv r.symm.toMulEquiv).injective
      rw [h_image]; exact hw_eq.symm
    have hw'_mem : w' ∈ GL2.TameLevel S := hw'_eq ▸ hw_mem
    -- The projection of `w'` at `v` is `g_loc`, hence `g_loc ∈ localFullLevel v`.
    have hg_loc_mem : g_loc ∈ GL2.localFullLevel v := by
      have := hw'_mem.1 v
      rwa [hw'_def,
        FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same v g_loc] at this
    -- Entry (0,1) of `g_loc`, which equals `α⁻¹ * (t_j - t_i)`, must be in `O_v`.
    have h01_int : ((g_loc : GL (Fin 2) (adicCompletion F v)) 0 1) ∈
        (adicCompletionIntegers F v) := GL2.v_le_one_of_mem_localFullLevel _ hg_loc_mem 0 1
    have hg_loc_val : g_loc = Matrix.GeneralLinearGroup.GL2.unipotent
        ((α : v.adicCompletion F)⁻¹ *
          ((t_j : adicCompletion F v) + -(t_i : adicCompletion F v))) := by
      exact Local.GL2.unipotent_mul_diag_inv_mul_unipotent_mul_diag α hα t_i t_j
    have h01_eq : ((g_loc : GL (Fin 2) (adicCompletion F v)) 0 1) =
        (α : v.adicCompletion F)⁻¹ *
          ((t_j : adicCompletion F v) + -(t_i : adicCompletion F v)) := by
      rw [hg_loc_val]
      simp [Matrix.GeneralLinearGroup.GL2.unipotent, Matrix.unitOfDetInvertible]
    rw [h01_eq] at h01_int
    -- Conclude `i = j` in `O_v / α`.
    change i = j
    rw [← (QuotientAddGroup.out_eq' i), ← (QuotientAddGroup.out_eq' j)]
    apply QuotientAddGroup.eq.mpr
    apply Ideal.mem_span_singleton'.mpr
    refine ⟨⟨_, h01_int⟩, ?_⟩
    apply (Subtype.coe_inj).mp
    push_cast
    rw [mul_comm ((α : v.adicCompletion F)⁻¹) _, mul_assoc,
      inv_mul_cancel₀ ((Subtype.coe_ne_coe).mpr hα), mul_one]
    ring
  · -- SurjOn: given `u ∈ U1 r S`, pull `u` back via `r` to `w ∈ GL2.TameLevel S`. The
    -- local surjOn at `v` provides `t : O_v/α` such that the local ratio lies in
    -- `localTameLevel v = U1 v` (using `v ∈ S`). We show that the preimage of the
    -- global ratio via `r` is in `GL2.TameLevel S` by checking at each place: at `v` it
    -- equals the local ratio, and at `w_place ≠ v` it equals the projection of `w` at
    -- `w_place`, which is in the appropriate local level since `w ∈ GL2.TameLevel S`.
    rintro _ ⟨_, ⟨u, hu, _, rfl, rfl⟩, rfl⟩
    -- Extract the preimage `w ∈ GL2.TameLevel S`.
    obtain ⟨w, hw_mem, hw_eq⟩ := Subgroup.mem_map.mp hu
    -- The projection of `w` at `v`.
    set g_loc : GL (Fin 2) (adicCompletion F v) :=
      FiniteAdeleRing.GL2.toAdicCompletion v w with hg_loc_def
    -- `g_loc ∈ localTameLevel v` because `v ∈ S` and `w ∈ GL2.TameLevel S`.
    have hg_loc_tame : g_loc ∈ GL2.localTameLevel v := hw_mem.2 v hv
    -- Apply the local surjOn.
    have hlocal_target :
        QuotientGroup.mk (g_loc * Local.GL2.diag α hα) ∈ Local.U1diagU1 v α hα :=
      ⟨_, Set.mul_mem_mul hg_loc_tame rfl, rfl⟩
    obtain ⟨t, _, ht⟩ :=
      Local.surjOn_unipotent_mul_diagU1_U1diagU1 α hα hlocal_target
    -- The local ratio lies in `Local.U1 v = localTameLevel v`.
    have hlocal_ratio :
        (Local.GL2.unipotent_mul_diag α hα
            (Quotient.out t : adicCompletionIntegers F v))⁻¹ *
          (g_loc * Local.GL2.diag α hα) ∈ Local.U1 v :=
      QuotientGroup.eq.mp ht
    refine ⟨unipotent_mul_diag r α hα t, ⟨t, trivial, rfl⟩, ?_⟩
    -- It suffices to show that the ratio is in `U1 r S`.
    apply QuotientGroup.eq.mpr
    refine Subgroup.mem_map.mpr ?_
    -- Build the global witness: the unique preimage `W ∈ GL₂(𝔸)` of the ratio under `r`.
    set W : GL (Fin 2) (FiniteAdeleRing (𝓞 F) F) :=
      (FiniteAdeleRing.GL2.restrictedProduct.symm
        (RestrictedProduct.mulSingle _ v
          (Local.GL2.unipotent_mul_diag α hα
            (Quotient.out t : adicCompletionIntegers F v))))⁻¹ *
      (w * FiniteAdeleRing.GL2.restrictedProduct.symm
        (RestrictedProduct.mulSingle _ v (Local.GL2.diag α hα))) with hW_def
    refine ⟨W, ?_, ?_⟩
    · -- Show `W ∈ GL2.TameLevel S`.
      refine ⟨fun w_place => ?_, fun w_place hwS => ?_⟩
      · by_cases hwv : w_place = v
        · subst hwv
          rw [hW_def]
          simp only [map_mul, map_inv]
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w_place _,
            FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w_place _]
          exact hlocal_ratio.1
        · rw [hW_def]
          simp only [map_mul, map_inv]
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _,
            FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          simp only [inv_one, one_mul, mul_one]
          exact hw_mem.1 w_place
      · by_cases hwv : w_place = v
        · subst hwv
          rw [hW_def]
          simp only [map_mul, map_inv]
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w_place _,
            FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w_place _]
          exact hlocal_ratio
        · rw [hW_def]
          simp only [map_mul, map_inv]
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _,
            FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          simp only [inv_one, one_mul, mul_one]
          exact hw_mem.2 w_place hwS
    · -- Show `Units.map r.symm.toMonoidHom W = ratio`.
      rw [← hw_eq]
      change Units.map r.symm.toMonoidHom W =
        (unipotent_mul_diag r α hα t)⁻¹ *
          (Units.map r.symm.toMonoidHom w * diag r α hα)
      rw [hW_def]
      simp only [map_mul, map_inv]
      rfl

omit [IsTotallyReal F] in
lemma unipotent_mul_diag_image_finite :
    (unipotent_mul_diag_image r α hα).Finite := by
  apply (Set.BijOn.finite_iff_finite
    (bijOn_unipotent_mul_diagU1_U1diagU1 r {v} α hα (Finset.mem_singleton.mpr rfl))).mpr
  unfold U1diagU1
  exact (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r {v}) (U1_open r {v}))

omit [IsTotallyReal F] in
lemma quot_top_finite (r : Rigidification F D) (α : v.adicCompletionIntegers F) (hα : α ≠ 0) :
    (⊤ : Set ((adicCompletionIntegers F v) ⧸ (Ideal.span {α}))).Finite := by
  apply Set.Finite.of_finite_image _ (unipotent_mul_diag_inj r α hα)
  apply unipotent_mul_diag_image_finite

set_option maxSynthPendingDepth 1 in -- shaves a little time off compilation!
/-- The Hecke operator U_{v,α} associated to the matrix (α 0;0 1) at v,
considered as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S). Here α is a nonzero element of 𝓞ᵥ.
We do not demand the condition v ∈ S, the bad primes, but this operator
should only be used in this setting. See also `T r v` for the good primes.
-/
noncomputable def U :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  AbstractHeckeOperator.HeckeOperator (R := R) (diag r α hα) (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_open r S))

lemma _root_.Ne.mul {M₀ : Type*} [Mul M₀] [Zero M₀] [NoZeroDivisors M₀] {a b : M₀}
  (ha : a ≠ 0) (hb : b ≠ 0) : a * b ≠ 0 := mul_ne_zero ha hb

noncomputable instance :
    DistribSMul (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ (WeightTwoAutomorphicForm F D R) :=
  distribMulAction.toDistribSMul

omit [IsTotallyReal F] in
lemma U_apply (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ((U r S R α hα) a).1 =
    ∑ᶠ (gᵢ : (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ) (_ : gᵢ ∈ Quotient.out '' (U1diagU1 r S α hα)),
      gᵢ • a.1 :=
  rfl

omit [IsTotallyReal F] in
open AbstractHeckeOperator in
lemma U_apply_eq_finsum_unipotent_mul_diag_image (hv : v ∈ S)
    (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ((U r S R α hα) a).1 =
    ∑ᶠ (g : (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ) (_ : g ∈ unipotent_mul_diag_image r α hα),
      g • a.1 :=
  (eq_finsum_quotient_out_of_bijOn' a (bijOn_unipotent_mul_diagU1_U1diagU1 r S α hα hv)) ▸
    U_apply r S R α hα a

/-- A "raw lift" version of `unipotent_mul_diag`: takes an arbitrary `t : 𝓞_v` instead of
a coset class. This is useful for manipulating products via the local matrix formula. -/
noncomputable def unipotent_mul_diag_lift (t : adicCompletionIntegers F v) :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _ (Local.GL2.unipotent_mul_diag α hα t)))

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
lemma unipotent_mul_diag_eq_lift (t : ↑(adicCompletionIntegers F v) ⧸ (Ideal.span {α})) :
    unipotent_mul_diag r α hα t = unipotent_mul_diag_lift r α hα (Quotient.out t) :=
  rfl

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
/-- The global multiplication formula for `unipotent_mul_diag_lift`: matches the local
matrix product formula `!![α,s;0,1] * !![β,t;0,1] = !![αβ, α*t+s; 0,1]`, transported
through the restricted product + rigidification pipeline. -/
lemma unipotent_mul_diag_lift_mul {β : v.adicCompletionIntegers F} (hβ : β ≠ 0)
    (s t : adicCompletionIntegers F v) :
    unipotent_mul_diag_lift r α hα s * unipotent_mul_diag_lift r β hβ t =
    unipotent_mul_diag_lift r (α * β) (mul_ne_zero hα hβ)
      ((α : adicCompletionIntegers F v) * t + s) := by
  simp only [unipotent_mul_diag_lift, ← map_mul, ← RestrictedProduct.mulSingle_mul]
  congr 3
  exact Local.GL2.unipotent_mul_diag_mul_unipotent_mul_diag α hα hβ s t

omit [IsTotallyReal F] in
/-- `U1`-invariance of `unipotent_mul_diag_lift` action: if `t₁ - t₂ ∈ (γ)`, then
`unipotent_mul_diag_lift γ t₁ • a = unipotent_mul_diag_lift γ t₂ • a` for any
`U1 r S`-fixed automorphic form `a`. -/
lemma unipotent_mul_diag_lift_smul_eq {γ : v.adicCompletionIntegers F} (hγ : γ ≠ 0)
    {t₁ t₂ : v.adicCompletionIntegers F}
    (h : t₁ - t₂ ∈ Ideal.span ({γ} : Set (v.adicCompletionIntegers F)))
    (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    unipotent_mul_diag_lift r γ hγ t₁ • a.1 =
      unipotent_mul_diag_lift r γ hγ t₂ • a.1 := by
  -- Strategy: write `lift t₁ = lift t₂ * u''` where `u'' = (lift t₂)⁻¹ * lift t₁ ∈ U1 r S`.
  -- Then `lift t₁ • a = lift t₂ • (u'' • a) = lift t₂ • a` using `a.2` on `u''`.
  set u'' : (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
    (unipotent_mul_diag_lift r γ hγ t₂)⁻¹ * unipotent_mul_diag_lift r γ hγ t₁ with hu''_def
  -- Obtain the ring element `m` with `t₁ - t₂ = m * γ`.
  obtain ⟨m, hm⟩ := Ideal.mem_span_singleton'.mp h
  -- Show `u''` is in `U1 r S` by exhibiting a witness in `GL2.TameLevel S`.
  have hu'' : u'' ∈ U1 r S := by
    refine Subgroup.mem_map.mpr ⟨?_, ?_, ?_⟩
    · -- The witness: the unit built from `mulSingle v (unipotent ↑m)`.
      exact FiniteAdeleRing.GL2.restrictedProduct.symm
        (RestrictedProduct.mulSingle _ _
          (Matrix.GeneralLinearGroup.GL2.unipotent (m : adicCompletion F v)))
    · -- The witness is in `GL2.TameLevel S`.
      refine ⟨?_, ?_⟩
      · intro w
        -- At every place `w`, the element is in `localFullLevel w`.
        by_cases hwv : w = v
        · subst hwv
          -- The image at `w = v` is `unipotent ↑m`, which is in `localFullLevel`.
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact (Local.GL2.unipotent_mem_U1 (v := w) m).1
        · -- The image at `w ≠ v` is `1`, which is in `localFullLevel`.
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localFullLevel w).one_mem
      · intro w hwS
        by_cases hwv : w = v
        · subst hwv
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact Local.GL2.unipotent_mem_U1 (v := w) m
        · rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localTameLevel w).one_mem
    · -- Applying `Units.map r.symm.toMonoidHom` to the witness yields `u''`.
      change Units.map r.symm.toMonoidHom _ = u''
      rw [hu''_def, unipotent_mul_diag_lift, unipotent_mul_diag_lift]
      change _ = (Units.mapEquiv r.symm.toMulEquiv _)⁻¹ *
        (Units.mapEquiv r.symm.toMulEquiv _)
      rw [← map_inv, ← map_mul]
      change Units.mapEquiv r.symm.toMulEquiv _ =
        Units.mapEquiv r.symm.toMulEquiv _
      congr 1
      rw [← map_inv, ← map_mul, ← RestrictedProduct.mulSingle_inv,
        ← RestrictedProduct.mulSingle_mul]
      congr 1
      rw [Local.GL2.unipotent_mul_diag_inv_mul_unipotent_mul_diag γ hγ t₂ t₁]
      congr 1
      -- Need: `(γ : adicCompletion F v)⁻¹ * (t₁ + -t₂) = m` (in `adicCompletion F v`).
      have hmval : ((t₁ : adicCompletion F v) + -(t₂ : adicCompletion F v)) =
          ((γ : adicCompletion F v)) * (m : adicCompletion F v) := by
        have hh : ((m : adicCompletion F v)) * (γ : adicCompletion F v) =
            (t₁ : adicCompletion F v) - (t₂ : adicCompletion F v) := by
          have := congrArg (fun x : v.adicCompletionIntegers F =>
            (x : adicCompletion F v)) hm
          push_cast at this
          exact this
        linear_combination -hh
      have hγne : (γ : adicCompletion F v) ≠ 0 := by exact_mod_cast hγ
      rw [hmval, ← mul_assoc, inv_mul_cancel₀ hγne, one_mul]
  -- Rewrite `lift t₁ = lift t₂ * u''`.
  have hlift : unipotent_mul_diag_lift r γ hγ t₁ =
      unipotent_mul_diag_lift r γ hγ t₂ * u'' := by
    rw [hu''_def, ← mul_assoc, mul_inv_cancel, one_mul]
  rw [hlift, mul_smul]
  -- Use `U1`-invariance of `a`.
  congr 1
  exact a.2 ⟨u'', hu''⟩

omit [IsTotallyReal F] in
lemma U_mul_aux {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0)
    (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ∑ᶠ (i : (adicCompletionIntegers F v) ⧸ Ideal.span {α})
      (j : (adicCompletionIntegers F v) ⧸ Ideal.span {β}),
      unipotent_mul_diag r α hα i • unipotent_mul_diag r β hβ j • a.1 =
    ∑ᶠ (k : (adicCompletionIntegers F v) ⧸ Ideal.span {α * β}),
      unipotent_mul_diag r (α * β) (hα.mul hβ) k • a.1 := by
  -- All three quotients are finite (deduced from `quot_top_finite`).
  have hfinα : Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({α} : Set _)) := by
    have := (quot_top_finite r α hα)
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  have hfinβ : Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({β} : Set _)) := by
    have := (quot_top_finite r β hβ)
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  have hfinαβ :
      Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({α * β} : Set _)) := by
    have := (quot_top_finite r (α * β) (mul_ne_zero hα hβ))
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  -- Combine the double finsum into one over the product, then transport via the bijection
  -- `prodEquivSpanMul`, and identify summands using the U1-invariance lemma.
  set Qα := v.adicCompletionIntegers F ⧸ Ideal.span ({α} : Set _) with hQα
  set Qβ := v.adicCompletionIntegers F ⧸ Ideal.span ({β} : Set _) with hQβ
  rw [show (∑ᶠ (i : Qα) (j : Qβ),
      unipotent_mul_diag r α hα i • unipotent_mul_diag r β hβ j • a.1) =
    ∑ᶠ (p : Qα × Qβ),
      unipotent_mul_diag r α hα p.1 • unipotent_mul_diag r β hβ p.2 • a.1 from
    (finsum_curry (α := Qα) (β := Qβ)
      (fun p => unipotent_mul_diag r α hα p.1 • unipotent_mul_diag r β hβ p.2 • a.1)
      (Set.toFinite _)).symm]
  rw [← finsum_comp_equiv (Ideal.Quotient.prodEquivSpanMul (β := β) hα)
    (f := fun (k : v.adicCompletionIntegers F ⧸ Ideal.span {α * β}) =>
      unipotent_mul_diag r (α * β) (hα.mul hβ) k • a.1)]
  refine finsum_congr (fun p => ?_)
  obtain ⟨i, j⟩ := p
  -- LHS: `(unipotent_mul_diag α i * unipotent_mul_diag β j) • a.1
  --      = unipotent_mul_diag_lift (α*β) (α * j.out + i.out) • a.1`.
  rw [unipotent_mul_diag_eq_lift, unipotent_mul_diag_eq_lift, ← mul_smul,
    unipotent_mul_diag_lift_mul, unipotent_mul_diag_eq_lift]
  -- Use U1-invariance: the two lifts differ by an element of `(α * β)`.
  apply unipotent_mul_diag_lift_smul_eq
  -- The bijection sends `(i,j) ↦ Ideal.Quotient.mk (i.out + α * j.out)`.
  change (α * j.out + i.out) -
    ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out ∈
      Ideal.span ({α * β} : Set _)
  have hkmk : (Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j) =
      Ideal.Quotient.mk (Ideal.span ({α * β} : Set _)) (i.out + α * j.out) := by
    unfold Ideal.Quotient.prodEquivSpanMul
    rfl
  have h1 :
      ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out - (i.out + α * j.out)
        ∈ Ideal.span ({α * β} : Set _) := by
    rw [← Ideal.Quotient.eq, Ideal.Quotient.mk_out, hkmk]
  have heq : (α * j.out + i.out) -
      ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out =
      -(((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out -
        (i.out + α * j.out)) := by ring
  rw [heq]; exact neg_mem h1

omit [IsTotallyReal F] in
open AbstractHeckeOperator in
lemma U_mul {v : HeightOneSpectrum (𝓞 F)} (hv : v ∈ S)
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    (U r S R α hα ∘ₗ U r S R β hβ) =
    U r S R (α * β) (hα.mul hβ) := by
  ext1 a
  apply (Subtype.coe_inj).mp
  simp only [U_apply_eq_finsum_unipotent_mul_diag_image _ _ _ _ _ hv,
    LinearMap.coe_comp, Function.comp_apply,
    smul_finsum_mem (unipotent_mul_diag_image_finite r β hβ)]
  unfold unipotent_mul_diag_image
  simp only [finsum_mem_image (unipotent_mul_diag_inj _ _ _)]
  simpa using U_mul_aux r S R hα hβ a

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
/-- Two `unipotent_mul_diag` elements at distinct places commute: they have
disjoint support in the restricted product. -/
lemma unipotent_mul_diag_commute_of_ne
    {v w : HeightOneSpectrum (𝓞 F)} (hvw : v ≠ w)
    {α : v.adicCompletionIntegers F} (hα : α ≠ 0)
    {β : w.adicCompletionIntegers F} (hβ : β ≠ 0)
    (i : ↑(adicCompletionIntegers F v) ⧸ (Ideal.span {α}))
    (j : ↑(adicCompletionIntegers F w) ⧸ (Ideal.span {β})) :
    Commute (unipotent_mul_diag r α hα i) (unipotent_mul_diag r β hβ j) := by
  unfold unipotent_mul_diag
  have hrp : Commute
      (RestrictedProduct.mulSingle
        (fun v : HeightOneSpectrum (𝓞 F) => (M2.localFullLevel v).units) v
        (Local.GL2.unipotent_mul_diag α hα
          (Quotient.out i : adicCompletionIntegers F v)))
      (RestrictedProduct.mulSingle
        (fun v : HeightOneSpectrum (𝓞 F) => (M2.localFullLevel v).units) w
        (Local.GL2.unipotent_mul_diag β hβ
          (Quotient.out j : adicCompletionIntegers F w))) :=
    RestrictedProduct.mulSingle_commute _ hvw _ _
  exact (hrp.map (FiniteAdeleRing.GL2.restrictedProduct (F := F)).symm.toMonoidHom).map
    (Units.mapEquiv r.symm.toMulEquiv).toMonoidHom

omit [IsTotallyReal F] in
lemma U_comm {v : HeightOneSpectrum (𝓞 F)} (hv : v ∈ S)
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    U r S R α hα ∘ₗ U r S R β hβ =
    U r S R β hβ ∘ₗ U r S R α hα := by
  rw [U_mul _ _ _ hv, U_mul _ _ _ hv]
  congr 1
  rw [mul_comm]

end U

end HeckeOperator

open HeckeOperator

/-- `HeckeAlgebra F D r S R` is the Hecke algebra associated to the weight 2
`R`-valued automorphic forms associated to the discriminant 1 totally definite
quaternion algebra `D` over the totally real field `F`, of level `U₁(S)` where `S` is
a finite set of nonzero primes `v` of `𝓞 F`. To make sense of this definition we choose
a rigidification `r`, that is, a fixed `𝔸_F^∞`-linear
isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`, enabling us to define level structures and
Hecke operators `Tᵥ` and `Uᵥ` using 2x2 matrices.

Details: `U₁(S)` is the subgroup of `(D ⊗[F] 𝔸_F^∞)ˣ` associated, via `r`, to the
matrices which are in `GL₂(𝓞ᵥ)` for all `v ∉ S` and which are of the form
`(a *; 0 a)` mod `v` for all `v ∈ S`. The Hecke algebra is defined to be the
sub-`R`-algebra of the weight 2 forms of level `U₁(S)` generated by the following
two kinds of Hecke operators: first there are the operators
`Tᵥ` associated to the matrices `(ϖᵥ 0; 0 1)` for `v ∉ S` (here `ϖᵥ ∈ 𝔸_F^∞` is a local
uniformiser supported at `v`). Second, there are the Hecke operators `Uᵥ,ₐ`
for `v ∈ S` and `0 ≠ αᵥ ∈ 𝓞ᵥ`, associated the matries `(αᵥ 0; 0 1)`.
These slightly nonstandard Hecke operators satisfy `Uᵥ,ₛ * Uᵥ,ₜ = Uᵥ,ₛₜ`
and in particular this Hecke algebra is commutative (Hecke operators supported
at distinct primes commute because the decomposition of the double cosets
into single cosets can be done purely locally).
-/
def HeckeAlgebra : Type _ :=
  (Algebra.adjoin R ({T r R v | v ∉ S} ∪
  {φ | ∃ (v : HeightOneSpectrum (𝓞 F)) (_hv : v ∈ S)
         (α : v.adicCompletionIntegers F) (hα : α ≠ 0), φ = U r S R α hα}) :
    Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

namespace HeckeAlgebra

noncomputable instance instRing :
    Ring (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Ring (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instAlgebra :
    Algebra R (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Algebra R (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

namespace HeckeOperator

set_option maxSynthPendingDepth 1 in
open scoped TensorProduct.RightActions in
omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
/-- The two diagonal group elements `diag(ϖ_v, 1)` and `diag(ϖ_w, 1)` (pulled back through
the rigidification `r`) commute unconditionally: diagonal matrices over a commutative ring
always commute. This is the group-theoretic fact underlying the commutativity of the
Hecke operators `T_v` and `T_w`; note however that commutation of the group elements
alone is *not* sufficient to deduce commutation of the associated Hecke operators —
that still requires a description of the double coset `U1 · diag(ϖ_v,1) · U1` as a union
of single cosets (see `AbstractHeckeOperator.comm`). -/
lemma T_diag_commute (v w : HeightOneSpectrum (𝓞 F)) :
    Commute
      (Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
        ![FiniteAdeleRing.localUniformiserUnit F v, 1]))
      (Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
        ![FiniteAdeleRing.localUniformiserUnit F w, 1])) := by
  refine Commute.map ?_ (Units.map r.symm.toMonoidHom)
  -- Two diagonal matrices over a commutative ring commute.
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.GeneralLinearGroup.diagonal, Matrix.diagonal, Fin.isValue,
          Matrix.cons_val_fin_one, Matrix.cons_val_zero, Matrix.cons_val_one,
          Matrix.mul_apply, mul_comm]

end HeckeOperator

set_option maxHeartbeats 1000000 in
-- Elaborating this instance exceeds the default heartbeat budget: the 4-way
-- case split under `Algebra.adjoinCommRingOfComm` triggers `whnf` on
-- `FiniteAdeleRing.GL2.restrictedProduct`, which is expensive to unfold.
noncomputable instance instCommRing :
    CommRing (HeckeAlgebra F D r S R) := by
  -- #585: reduce commutativity of the Hecke algebra to pairwise commutativity of the
  -- generators `Tᵥ` (for `v ∉ S`) and `Uᵥ,α` (for `v ∈ S`, `α ≠ 0`).
  unfold HeckeAlgebra
  apply Algebra.adjoinCommRingOfComm R
  rintro a ha b hb
  -- Case split on `ha`, `hb` to handle the four generator pairs:
  --   (T_v, T_w), (T_v, U_{w,β}), (U_{v,α}, T_w), (U_{v,α}, U_{w,β}).
  rcases ha with ⟨v, hv, rfl⟩ | ⟨v, hv, α, hα, rfl⟩ <;>
  rcases hb with ⟨w, hw, rfl⟩ | ⟨w, hw, β, hβ, rfl⟩
  · -- (T_v, T_w): Hecke operators at good primes commute. Follows from the fact that
    -- the coset representatives `diag(ϖ_v,1)` and `diag(ϖ_w,1)` have disjoint support
    -- in the restricted product when v ≠ w (and trivially when v = w).
    by_cases hvw : v = w
    · -- v = w: T_v = T_w, so the product commutes with itself trivially.
      subst hvw
      rfl
    · -- v ≠ w: disjoint support argument via `AbstractHeckeOperator.comm`.
      -- TODO: Blocked on missing infrastructure. `AbstractHeckeOperator.comm` requires a
      -- `Set.BijOn QuotientGroup.mk s (QuotientGroup.mk '' (U1 * {diag(ϖ_v,1)}))` witness
      -- exhibiting a concrete set `s` of v-supported left-coset representatives for the
      -- double coset `U1 · diag(ϖ_v,1) · U1`. The only such witness currently in the
      -- codebase is `bijOn_unipotent_mul_diagU1_U1diagU1`, which is proven only for
      -- `v ∈ S` (where U1 at v is the Iwahori-style subgroup and the double coset has
      -- |O_v / α| single cosets). For `v ∉ S`, U1 at v is the full maximal compact
      -- `GL₂(𝒪_v)` and the classical `T_v` double coset decomposes into q+1 single
      -- cosets (`diag(ϖ_v,1)` and `(1 t; 0 ϖ_v)` for `t` in 𝒪_v/ϖ_v), but no analogue of
      -- `bijOn_unipotent_mul_diagU1_U1diagU1` has been built for this case. Closing this
      -- sorry requires adding (a) a local lemma in Local.lean giving a BijOn for the
      -- T_v double coset at a good prime, and (b) the global lift mirroring
      -- `bijOn_unipotent_mul_diagU1_U1diagU1` in this file.
      sorry
  · -- (T_v, U_{w,β}): good prime T_v commutes with bad prime U_{w,β}. Since v ∉ S and
    -- w ∈ S, we have v ≠ w, so the representatives are supported at disjoint places.
    -- TODO: Blocked on the same missing T_v coset-representative infrastructure as the
    -- (T_v, T_w) case above. The U_{w,β} side has
    -- `bijOn_unipotent_mul_diagU1_U1diagU1 r S β hβ hw` available, but the T_v side
    -- still needs a BijOn witness for `U1 · diag(ϖ_v,1) · U1` before
    -- `AbstractHeckeOperator.comm` can be applied.
    sorry
  · -- (U_{v,α}, T_w): symmetric to the previous case.
    -- TODO: Blocked on the same missing T_w coset-representative infrastructure.
    sorry
  · -- (U_{v,α}, U_{w,β}): bad prime operators.
    by_cases hvw : v = w
    · -- v = w: use `HeckeOperator.U_comm`. Need to transport `hβ` across `hvw`.
      subst hvw
      change HeckeOperator.U r S R α hα * HeckeOperator.U r S R β hβ =
        HeckeOperator.U r S R β hβ * HeckeOperator.U r S R α hα
      exact HeckeOperator.U_comm r S R hv hα hβ
    · -- v ≠ w: disjoint support argument via `AbstractHeckeOperator.comm`.
      change HeckeOperator.U r S R α hα * HeckeOperator.U r S R β hβ =
        HeckeOperator.U r S R β hβ * HeckeOperator.U r S R α hα
      unfold HeckeOperator.U
      apply AbstractHeckeOperator.comm (R := R)
      refine ⟨unipotent_mul_diag_image r α hα, unipotent_mul_diag_image r β hβ,
        bijOn_unipotent_mul_diagU1_U1diagU1 r S α hα hv,
        bijOn_unipotent_mul_diagU1_U1diagU1 r S β hβ hw, ?_⟩
      rintro a ⟨i, _, rfl⟩ b ⟨j, _, rfl⟩
      -- `unipotent_mul_diag r α hα i` is supported at `v` and
      -- `unipotent_mul_diag r β hβ j` is supported at `w`, with `v ≠ w`, so they commute.
      exact (HeckeOperator.unipotent_mul_diag_commute_of_ne r hvw hα hβ i j).eq

variable {F S} in
/-- The Hecke operator Tᵥ as an element of the Hecke algebra. -/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) (hv : v ∉ S) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.T r R v, by
    apply Algebra.subset_adjoin
    left
    use v⟩

variable {F S} in
/-- The Hecke operator Uᵥ,ₐ as an element of the Hecke algebra. -/
noncomputable def U (v : HeightOneSpectrum (𝓞 F)) (hv : v ∈ S) (α : v.adicCompletionIntegers F)
    (hα : α ≠ 0) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.U r S R α hα, by
    apply Algebra.subset_adjoin
    right
    use v, hv, α, hα⟩

end HeckeAlgebra

end TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm
