/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard, Andrew Yang, Matthew Jasper
-/
import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Local -- abstract Hecke ops
import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Abstract -- abstract Hecke ops
import FLT.AutomorphicForm.QuaternionAlgebra.Defs -- definitions of automorphic forms
import FLT.QuaternionAlgebra.NumberField -- rigidifications of quat algs
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.RingTheory.DedekindDomain.FiniteAdeleRing
import FLT.DedekindDomain.FiniteAdeleRing.LocalUnits -- for (π 0; 0 1)
import FLT.Mathlib.Topology.Algebra.RestrictedProduct.TopologicalSpace
import FLT.Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
/-

# Concrete Hecke operators

Hecke operators for spaces of automorphic forms on totally definite quaternion algebras
of level `U₁(S)`, where `S` is a finite set of finite places of the totally real number
field `F`, and `U₁(S)` is the matrices which are of the form `(a *;0 a)` mod `v` for
all `v ∈ S`.

## Main definitions

All in the `TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm` namespace.

Let `r : Rigidification F D` be an `𝔸_F^∞`-algebra isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`,
needed to interpret the local factors `Dᵥ` as matrix rings so we can define Hecke operators
as matrices.

* `HeckeOperator.T r R v` -- the Hecke operator `Tᵥ` associated to `(ϖᵥ 0; 0 1)` at a (good)
  place `v` (via the rigidification `r`), as an `R`-linear endomorphism of
  `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeOperator.U r S R a ha` -- the Hecke operator `Uᵥ,ₐ` associated to `(a 0;0 1)` at
  a (bad) place `v`; here `a : v.adicCompletionIntegers F` and `ha` is a proof that `a ≠ 0`,
  as an `R`-linear endomorphism of `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeAlgebra F D r S R` -- the Hecke algebra generated by the `Tᵥ` and `Uᵥ,ₐ`. Built
  as a type, coerced from a subalgebra of the endomorphism algebra of the forms.
* `HeckeAlgebra.T D r R v hv` -- `Tᵥ` as a term of type `HeckeAlgebra F D r S R`
* `HeckeAlgebra.U D r R v hv a ha` -- `Uᵥ,ₐ` as a term of type `HeckeAlgebra F D r S R`

-/

/-

## A finiteness result

The existence of abstract Hecke operators relies on a certain double coset space being
a finite union of single cosets. In our situation we can supply this finiteness proof
via a topological argument, which we abstract here.

-/

section finiteness

open Topology Set

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {g : G} {U V : Subgroup G}

open scoped Pointwise in
lemma QuotientGroup.mk_image_finite_of_compact_of_open
    (hU : IsCompact (U : Set G)) (hVopen : IsOpen (V : Set G)) :
    (QuotientGroup.mk '' (U * {g}) : Set (G ⧸ V)).Finite := by
  have : DiscreteTopology (G ⧸ V) := by
    rw [discreteTopology_iff_forall_isOpen]
    intro s
    rw [← (isQuotientMap_mk V).isOpen_preimage, ← (QuotientGroup.mk_surjective).image_preimage s,
      preimage_image_mk_eq_iUnion_image, iUnion_subtype]
    conv in ⋃ x ∈ _, _ => change ⋃ x ∈ (V : Set G), _
    rw [iUnion_mul_right_image]
    exact IsOpen.mul_left hVopen
  exact ((hU.mul <| isCompact_singleton).image continuous_mk).finite_of_discrete

end finiteness


open NumberField IsQuaternionAlgebra.NumberField IsDedekindDomain

-- let F be a totally real number field
variable (F : Type*) [Field F] [NumberField F] [IsTotallyReal F]

-- Let D/F be a quaternion algebra
variable (D : Type*) [Ring D] [Algebra F D] [IsQuaternionAlgebra F D]

-- Let r be a rigidification of D, which is a collection of isomorphisms D ⊗ Fᵥ = M₂(Fᵥ)
-- for all finite places v of F, compatible with the adelic structure (i.e. inducing
-- an isomorphism D ⊗_F 𝔸_F^f = M₂(𝔸_F^f))
variable (r : Rigidification F D)

-- Let S be a finite set of finite plaes of F (the level)
variable (S : Finset (HeightOneSpectrum (𝓞 F)))

-- let P be a good prime
variable {P : HeightOneSpectrum (𝓞 F)} (hP : P ∉ S)

open TotallyDefiniteQuaternionAlgebra
-- let's define T_P : S_2^D(U_1(S)) -> S_2^D(U_1(S))
namespace TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm

open IsDedekindDomain.HeightOneSpectrum

open scoped TensorProduct

-- Oops! This is also `IsDedekindDomain.HeightOneSpectrum.QuaternionAlgebra.TameLevel`
-- in `FLT.QuaternionAlgebra.NumberField`, defined differently (using `Subgroup.comap` not `map`).
-- Don't care which one survives.
variable {F D} in
open scoped TensorProduct.RightActions in
/-- U1(S) -/
noncomputable abbrev U1 : Subgroup (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
  Subgroup.map (Units.map r.symm.toMonoidHom) (GL2.TameLevel S)

omit [IsTotallyReal F] in
variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_compact :
    IsCompact (U1 r S :
      Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) := by
  rw [U1, Subgroup.coe_map]
  have hc : Continuous r.symm :=
    IsDedekindDomain.HeightOneSpectrum.Rigidification.continuous_invFun D r
  exact (GL2.TameLevel.isCompact S).image
    (Continuous.units_map r.symm.toMonoidHom hc)

omit [IsTotallyReal F] in
variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_open :
    IsOpen (U1 r S :
      Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) := by
  rw [U1, Subgroup.coe_map]
  have hcr : Continuous r :=
    IsDedekindDomain.HeightOneSpectrum.Rigidification.continuous_toFun D r
  rw [Set.image_eq_preimage_of_inverse
    (f := Units.map r.symm.toMonoidHom)
    (g := Units.map r.toMonoidHom)
    (fun x => by ext; simp) (fun x => by ext; simp)]
  exact (GL2.TameLevel.isOpen S).preimage
    (Continuous.units_map r.toMonoidHom hcr)

variable (R : Type*) [CommRing R]

namespace HeckeOperator

variable {F D S} in
set_option maxSynthPendingDepth 1 in
open scoped TensorProduct.RightActions in
/-- The Hecke operator T_v as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S).
-/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  letI : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _
  let g : (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
    Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
    ![FiniteAdeleRing.localUniformiserUnit F v, 1])
  AbstractHeckeOperator.HeckeOperator (R := R) g (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_open r S))

section U

variable {F D}

variable {v : HeightOneSpectrum (𝓞 F)} (α : v.adicCompletionIntegers F) (hα : α ≠ 0)

open scoped TensorProduct.RightActions
open scoped Pointwise

noncomputable instance : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _

/-- The (global) matrix element `diag[α, 1]`. -/
noncomputable abbrev diag :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _ (Local.GL2.diag α hα)))

/-- The (global) matrix element `(unipotent t) * (diag α hα) = !![α, t; 0, 1]`.
Here `t ∈ 𝒪ᵥ / α` and we lift it arbitrarily to `𝒪ᵥ`. -/
noncomputable def unipotent_mul_diag (t : ↑(adicCompletionIntegers F v) ⧸ (Ideal.span {α})) :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _
      (Local.GL2.unipotent_mul_diag α hα (Quotient.out t : adicCompletionIntegers F v))))

/-- The set of elements `unipotent_mul_diag`, that is, the elements of `(D ⊗ 𝔸_F^∞)ˣ`
which are `(α t;0 1)` at `v` and the identity elsewhere, as `t` runs through a set
of coset reps of `𝓞ᵥ / α`. These will form a set of coset representatives for `U1 diag U1`.
-/
noncomputable def unipotent_mul_diag_image :
    Set (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  (unipotent_mul_diag r α hα) '' ⊤

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
lemma unipotent_mul_diag_inj :
    Set.InjOn (unipotent_mul_diag r α hα) ⊤ := by
  intro t₁ h₁ t₂ h₂ h
  simp only [unipotent_mul_diag, EmbeddingLike.apply_eq_iff_eq, RestrictedProduct.ext_iff] at h
  let h' := h v; simp only [RestrictedProduct.mulSingle_eq_same, Units.ext_iff] at h'
  rw [← Matrix.ext_iff] at h'
  let h'' := h' 0 1
  simpa [Local.GL2.unipotent_mul_diag, Matrix.GeneralLinearGroup.GL2.unipotent, Local.GL2.diag,
    Matrix.unitOfDetInvertible, Matrix.GeneralLinearGroup.diagonal] using h''

/-- The double coset space `U₁(S) diag(αᵥ,1) U₁(S)` as a set of left cosets. -/
noncomputable def U1diagU1 :
    Set ((D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ ⧸ (U1 r S)) :=
  QuotientGroup.mk '' ((U1 r S) * {diag r α hα})

theorem bijOn_unipotent_mul_diagU1_U1diagU1 :
    (unipotent_mul_diag_image r α hα).BijOn QuotientGroup.mk (U1diagU1 r S α hα) :=
  sorry -- global double coset decomposition

lemma unipotent_mul_diag_image_finite :
    (unipotent_mul_diag_image r α hα).Finite := by
  apply (Set.BijOn.finite_iff_finite (bijOn_unipotent_mul_diagU1_U1diagU1 r {v} α hα)).mpr
  unfold U1diagU1
  exact (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r {v}) (U1_open r {v}))

lemma quot_top_finite (r : Rigidification F D) (α : v.adicCompletionIntegers F) (hα : α ≠ 0) :
    (⊤ : Set ((adicCompletionIntegers F v) ⧸ (Ideal.span {α}))).Finite := by
  apply Set.Finite.of_finite_image _ (unipotent_mul_diag_inj r α hα)
  apply unipotent_mul_diag_image_finite

set_option maxSynthPendingDepth 1 in -- shaves a little time off compilation!
/-- The Hecke operator U_{v,α} associated to the matrix (α 0;0 1) at v,
considered as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S). Here α is a nonzero element of 𝓞ᵥ.
We do not demand the condition v ∈ S, the bad primes, but this operator
should only be used in this setting. See also `T r v` for the good primes.
-/
noncomputable def U :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  AbstractHeckeOperator.HeckeOperator (R := R) (diag r α hα) (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_open r S))

lemma _root_.Ne.mul {M₀ : Type*} [Mul M₀] [Zero M₀] [NoZeroDivisors M₀] {a b : M₀}
  (ha : a ≠ 0) (hb : b ≠ 0) : a * b ≠ 0 := mul_ne_zero ha hb

noncomputable instance :
    DistribSMul (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ (WeightTwoAutomorphicForm F D R) :=
  distribMulAction.toDistribSMul

omit [IsTotallyReal F] in
lemma U_apply (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ((U r S R α hα) a).1 =
    ∑ᶠ (gᵢ : (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ) (_ : gᵢ ∈ Quotient.out '' (U1diagU1 r S α hα)),
      gᵢ • a.1 :=
  rfl

open AbstractHeckeOperator in
lemma U_apply_eq_finsum_unipotent_mul_diag_image (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ((U r S R α hα) a).1 =
    ∑ᶠ (g : (D ⊗[F] FiniteAdeleRing (𝓞 F) F)ˣ) (_ : g ∈ unipotent_mul_diag_image r α hα),
      g • a.1 :=
  (eq_finsum_quotient_out_of_bijOn' a (bijOn_unipotent_mul_diagU1_U1diagU1 r S α hα)) ▸
    U_apply r S R α hα a

/-- A "raw lift" version of `unipotent_mul_diag`: takes an arbitrary `t : 𝓞_v` instead of
a coset class. This is useful for manipulating products via the local matrix formula. -/
noncomputable def unipotent_mul_diag_lift (t : adicCompletionIntegers F v) :
    (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
  Units.mapEquiv r.symm.toMulEquiv
    (FiniteAdeleRing.GL2.restrictedProduct.symm
    (RestrictedProduct.mulSingle _ _ (Local.GL2.unipotent_mul_diag α hα t)))

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
lemma unipotent_mul_diag_eq_lift (t : ↑(adicCompletionIntegers F v) ⧸ (Ideal.span {α})) :
    unipotent_mul_diag r α hα t = unipotent_mul_diag_lift r α hα (Quotient.out t) :=
  rfl

omit [IsTotallyReal F] [IsQuaternionAlgebra F D] in
/-- The global multiplication formula for `unipotent_mul_diag_lift`: matches the local
matrix product formula `!![α,s;0,1] * !![β,t;0,1] = !![αβ, α*t+s; 0,1]`, transported
through the restricted product + rigidification pipeline. -/
lemma unipotent_mul_diag_lift_mul {β : v.adicCompletionIntegers F} (hβ : β ≠ 0)
    (s t : adicCompletionIntegers F v) :
    unipotent_mul_diag_lift r α hα s * unipotent_mul_diag_lift r β hβ t =
    unipotent_mul_diag_lift r (α * β) (mul_ne_zero hα hβ)
      ((α : adicCompletionIntegers F v) * t + s) := by
  simp only [unipotent_mul_diag_lift, ← map_mul, ← RestrictedProduct.mulSingle_mul]
  congr 3
  exact Local.GL2.unipotent_mul_diag_mul_unipotent_mul_diag α hα hβ s t

omit [IsTotallyReal F] in
/-- `U1`-invariance of `unipotent_mul_diag_lift` action: if `t₁ - t₂ ∈ (γ)`, then
`unipotent_mul_diag_lift γ t₁ • a = unipotent_mul_diag_lift γ t₂ • a` for any
`U1 r S`-fixed automorphic form `a`. -/
lemma unipotent_mul_diag_lift_smul_eq {γ : v.adicCompletionIntegers F} (hγ : γ ≠ 0)
    {t₁ t₂ : v.adicCompletionIntegers F}
    (h : t₁ - t₂ ∈ Ideal.span ({γ} : Set (v.adicCompletionIntegers F)))
    (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    unipotent_mul_diag_lift r γ hγ t₁ • a.1 =
      unipotent_mul_diag_lift r γ hγ t₂ • a.1 := by
  -- Strategy: write `lift t₁ = lift t₂ * u''` where `u'' = (lift t₂)⁻¹ * lift t₁ ∈ U1 r S`.
  -- Then `lift t₁ • a = lift t₂ • (u'' • a) = lift t₂ • a` using `a.2` on `u''`.
  set u'' : (D ⊗[F] (FiniteAdeleRing (𝓞 F) F))ˣ :=
    (unipotent_mul_diag_lift r γ hγ t₂)⁻¹ * unipotent_mul_diag_lift r γ hγ t₁ with hu''_def
  -- Obtain the ring element `m` with `t₁ - t₂ = m * γ`.
  obtain ⟨m, hm⟩ := Ideal.mem_span_singleton'.mp h
  -- Show `u''` is in `U1 r S` by exhibiting a witness in `GL2.TameLevel S`.
  have hu'' : u'' ∈ U1 r S := by
    refine Subgroup.mem_map.mpr ⟨?_, ?_, ?_⟩
    · -- The witness: the unit built from `mulSingle v (unipotent ↑m)`.
      exact FiniteAdeleRing.GL2.restrictedProduct.symm
        (RestrictedProduct.mulSingle _ _
          (Matrix.GeneralLinearGroup.GL2.unipotent (m : adicCompletion F v)))
    · -- The witness is in `GL2.TameLevel S`.
      refine ⟨?_, ?_⟩
      · intro w
        -- At every place `w`, the element is in `localFullLevel w`.
        by_cases hwv : w = v
        · subst hwv
          -- The image at `w = v` is `unipotent ↑m`, which is in `localFullLevel`.
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact (Local.GL2.unipotent_mem_U1 (v := w) m).1
        · -- The image at `w ≠ v` is `1`, which is in `localFullLevel`.
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localFullLevel w).one_mem
      · intro w hwS
        by_cases hwv : w = v
        · subst hwv
          rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_same w _]
          exact Local.GL2.unipotent_mem_U1 (v := w) m
        · rw [FiniteAdeleRing.GL2.toAdicCompletion_restrictedProduct_symm_mulSingle_ne hwv _]
          exact (GL2.localTameLevel w).one_mem
    · -- Applying `Units.map r.symm.toMonoidHom` to the witness yields `u''`.
      change Units.map r.symm.toMonoidHom _ = u''
      rw [hu''_def, unipotent_mul_diag_lift, unipotent_mul_diag_lift]
      change _ = (Units.mapEquiv r.symm.toMulEquiv _)⁻¹ *
        (Units.mapEquiv r.symm.toMulEquiv _)
      rw [← map_inv, ← map_mul]
      change Units.mapEquiv r.symm.toMulEquiv _ =
        Units.mapEquiv r.symm.toMulEquiv _
      congr 1
      rw [← map_inv, ← map_mul, ← RestrictedProduct.mulSingle_inv,
        ← RestrictedProduct.mulSingle_mul]
      congr 1
      rw [Local.GL2.unipotent_mul_diag_inv_mul_unipotent_mul_diag γ hγ t₂ t₁]
      congr 1
      -- Need: `(γ : adicCompletion F v)⁻¹ * (t₁ + -t₂) = m` (in `adicCompletion F v`).
      have hmval : ((t₁ : adicCompletion F v) + -(t₂ : adicCompletion F v)) =
          ((γ : adicCompletion F v)) * (m : adicCompletion F v) := by
        have hh : ((m : adicCompletion F v)) * (γ : adicCompletion F v) =
            (t₁ : adicCompletion F v) - (t₂ : adicCompletion F v) := by
          have := congrArg (fun x : v.adicCompletionIntegers F =>
            (x : adicCompletion F v)) hm
          push_cast at this
          exact this
        linear_combination -hh
      have hγne : (γ : adicCompletion F v) ≠ 0 := by exact_mod_cast hγ
      rw [hmval, ← mul_assoc, inv_mul_cancel₀ hγne, one_mul]
  -- Rewrite `lift t₁ = lift t₂ * u''`.
  have hlift : unipotent_mul_diag_lift r γ hγ t₁ =
      unipotent_mul_diag_lift r γ hγ t₂ * u'' := by
    rw [hu''_def, ← mul_assoc, mul_inv_cancel, one_mul]
  rw [hlift, mul_smul]
  -- Use `U1`-invariance of `a`.
  congr 1
  exact a.2 ⟨u'', hu''⟩

lemma U_mul_aux {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0)
    (a : WeightTwoAutomorphicFormOfLevel (U1 r S) R) :
    ∑ᶠ (i : (adicCompletionIntegers F v) ⧸ Ideal.span {α})
      (j : (adicCompletionIntegers F v) ⧸ Ideal.span {β}),
      unipotent_mul_diag r α hα i • unipotent_mul_diag r β hβ j • a.1 =
    ∑ᶠ (k : (adicCompletionIntegers F v) ⧸ Ideal.span {α * β}),
      unipotent_mul_diag r (α * β) (hα.mul hβ) k • a.1 := by
  -- All three quotients are finite (deduced from `quot_top_finite`).
  have hfinα : Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({α} : Set _)) := by
    have := (quot_top_finite r α hα)
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  have hfinβ : Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({β} : Set _)) := by
    have := (quot_top_finite r β hβ)
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  have hfinαβ :
      Finite (v.adicCompletionIntegers F ⧸ Ideal.span ({α * β} : Set _)) := by
    have := (quot_top_finite r (α * β) (mul_ne_zero hα hβ))
    rw [Set.top_eq_univ, Set.finite_univ_iff] at this; exact this
  -- Combine the double finsum into one over the product, then transport via the bijection
  -- `prodEquivSpanMul`, and identify summands using the U1-invariance lemma.
  set Qα := v.adicCompletionIntegers F ⧸ Ideal.span ({α} : Set _) with hQα
  set Qβ := v.adicCompletionIntegers F ⧸ Ideal.span ({β} : Set _) with hQβ
  rw [show (∑ᶠ (i : Qα) (j : Qβ),
      unipotent_mul_diag r α hα i • unipotent_mul_diag r β hβ j • a.1) =
    ∑ᶠ (p : Qα × Qβ),
      unipotent_mul_diag r α hα p.1 • unipotent_mul_diag r β hβ p.2 • a.1 from
    (finsum_curry (α := Qα) (β := Qβ)
      (fun p => unipotent_mul_diag r α hα p.1 • unipotent_mul_diag r β hβ p.2 • a.1)
      (Set.toFinite _)).symm]
  rw [← finsum_comp_equiv (Ideal.Quotient.prodEquivSpanMul (β := β) hα)
    (f := fun (k : v.adicCompletionIntegers F ⧸ Ideal.span {α * β}) =>
      unipotent_mul_diag r (α * β) (hα.mul hβ) k • a.1)]
  refine finsum_congr (fun p => ?_)
  obtain ⟨i, j⟩ := p
  -- LHS: `(unipotent_mul_diag α i * unipotent_mul_diag β j) • a.1
  --      = unipotent_mul_diag_lift (α*β) (α * j.out + i.out) • a.1`.
  rw [unipotent_mul_diag_eq_lift, unipotent_mul_diag_eq_lift, ← mul_smul,
    unipotent_mul_diag_lift_mul, unipotent_mul_diag_eq_lift]
  -- Use U1-invariance: the two lifts differ by an element of `(α * β)`.
  apply unipotent_mul_diag_lift_smul_eq
  -- The bijection sends `(i,j) ↦ Ideal.Quotient.mk (i.out + α * j.out)`.
  change (α * j.out + i.out) -
    ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out ∈
      Ideal.span ({α * β} : Set _)
  have hkmk : (Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j) =
      Ideal.Quotient.mk (Ideal.span ({α * β} : Set _)) (i.out + α * j.out) := by
    unfold Ideal.Quotient.prodEquivSpanMul
    rfl
  have h1 :
      ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out - (i.out + α * j.out)
        ∈ Ideal.span ({α * β} : Set _) := by
    rw [← Ideal.Quotient.eq, Ideal.Quotient.mk_out, hkmk]
  have heq : (α * j.out + i.out) -
      ((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out =
      -(((Ideal.Quotient.prodEquivSpanMul (β := β) hα) (i, j)).out -
        (i.out + α * j.out)) := by ring
  rw [heq]; exact neg_mem h1

open AbstractHeckeOperator in
lemma U_mul {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    (U r S R α hα ∘ₗ U r S R β hβ) =
    U r S R (α * β) (hα.mul hβ) := by
  ext1 a
  apply (Subtype.coe_inj).mp
  simp only [U_apply_eq_finsum_unipotent_mul_diag_image,
    LinearMap.coe_comp, Function.comp_apply,
    smul_finsum_mem (unipotent_mul_diag_image_finite r β hβ)]
  unfold unipotent_mul_diag_image
  simp only [finsum_mem_image (unipotent_mul_diag_inj _ _ _)]
  simpa using U_mul_aux r S R hα hβ a

lemma U_comm {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    U r S R α hα ∘ₗ U r S R β hβ =
    U r S R β hβ ∘ₗ U r S R α hα := by
  rw [U_mul, U_mul]
  congr 1
  rw [mul_comm]

end U

end HeckeOperator

open HeckeOperator

/-- `HeckeAlgebra F D r S R` is the Hecke algebra associated to the weight 2
`R`-valued automorphic forms associated to the discriminant 1 totally definite
quaternion algebra `D` over the totally real field `F`, of level `U₁(S)` where `S` is
a finite set of nonzero primes `v` of `𝓞 F`. To make sense of this definition we choose
a rigidification `r`, that is, a fixed `𝔸_F^∞`-linear
isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`, enabling us to define level structures and
Hecke operators `Tᵥ` and `Uᵥ` using 2x2 matrices.

Details: `U₁(S)` is the subgroup of `(D ⊗[F] 𝔸_F^∞)ˣ` associated, via `r`, to the
matrices which are in `GL₂(𝓞ᵥ)` for all `v ∉ S` and which are of the form
`(a *; 0 a)` mod `v` for all `v ∈ S`. The Hecke algebra is defined to be the
sub-`R`-algebra of the weight 2 forms of level `U₁(S)` generated by the following
two kinds of Hecke operators: first there are the operators
`Tᵥ` associated to the matrices `(ϖᵥ 0; 0 1)` for `v ∉ S` (here `ϖᵥ ∈ 𝔸_F^∞` is a local
uniformiser supported at `v`). Second, there are the Hecke operators `Uᵥ,ₐ`
for `v ∈ S` and `0 ≠ αᵥ ∈ 𝓞ᵥ`, associated the matries `(αᵥ 0; 0 1)`.
These slightly nonstandard Hecke operators satisfy `Uᵥ,ₛ * Uᵥ,ₜ = Uᵥ,ₛₜ`
and in particular this Hecke algebra is commutative (Hecke operators supported
at distinct primes commute because the decomposition of the double cosets
into single cosets can be done purely locally).
-/
def HeckeAlgebra : Type _ :=
  (Algebra.adjoin R ({T r R v | v ∉ S} ∪
  {φ | ∃ (v : HeightOneSpectrum (𝓞 F)) (_hv : v ∈ S)
         (α : v.adicCompletionIntegers F) (hα : α ≠ 0), φ = U r S R α hα}) :
    Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

namespace HeckeAlgebra

noncomputable instance instRing :
    Ring (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Ring (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instAlgebra :
    Algebra R (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Algebra R (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instCommRing :
    CommRing (HeckeAlgebra F D r S R) := by
  -- #585: reduce commutativity of the Hecke algebra to pairwise commutativity of the
  -- generators `Tᵥ` (for `v ∉ S`) and `Uᵥ,α` (for `v ∈ S`, `α ≠ 0`).
  unfold HeckeAlgebra
  apply Algebra.adjoinCommRingOfComm R
  rintro a ha b hb
  -- Case split on `ha`, `hb` to handle the four generator pairs:
  --   (T_v, T_w), (T_v, U_{w,β}), (U_{v,α}, T_w), (U_{v,α}, U_{w,β}).
  rcases ha with ⟨v, hv, rfl⟩ | ⟨v, hv, α, hα, rfl⟩ <;>
  rcases hb with ⟨w, hw, rfl⟩ | ⟨w, hw, β, hβ, rfl⟩
  · -- (T_v, T_w): Hecke operators at good primes commute. Follows from the fact that
    -- the coset representatives `diag(ϖ_v,1)` and `diag(ϖ_w,1)` have disjoint support
    -- in the restricted product when v ≠ w (and trivially when v = w).
    by_cases hvw : v = w
    · -- v = w: T_v = T_w, so the product commutes with itself trivially.
      subst hvw
      rfl
    · -- v ≠ w: disjoint support argument via `AbstractHeckeOperator.comm`.
      sorry
  · -- (T_v, U_{w,β}): good prime T_v commutes with bad prime U_{w,β}. Since v ∉ S and
    -- w ∈ S, we have v ≠ w, so the representatives are supported at disjoint places.
    sorry
  · -- (U_{v,α}, T_w): symmetric to the previous case.
    sorry
  · -- (U_{v,α}, U_{w,β}): bad prime operators.
    by_cases hvw : v = w
    · -- v = w: use `HeckeOperator.U_comm`. Need to transport `hβ` across `hvw`.
      subst hvw
      change HeckeOperator.U r S R α hα * HeckeOperator.U r S R β hβ =
        HeckeOperator.U r S R β hβ * HeckeOperator.U r S R α hα
      exact HeckeOperator.U_comm r S R hα hβ
    · -- v ≠ w: disjoint support argument.
      sorry

variable {F S} in
/-- The Hecke operator Tᵥ as an element of the Hecke algebra. -/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) (hv : v ∉ S) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.T r R v, by
    apply Algebra.subset_adjoin
    left
    use v⟩

variable {F S} in
/-- The Hecke operator Uᵥ,ₐ as an element of the Hecke algebra. -/
noncomputable def U (v : HeightOneSpectrum (𝓞 F)) (hv : v ∈ S) (α : v.adicCompletionIntegers F)
    (hα : α ≠ 0) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.U r S R α hα, by
    apply Algebra.subset_adjoin
    right
    use v, hv, α, hα⟩

end HeckeAlgebra

end TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm
