import FLT.Data.Hurwitz
import FLT.Data.QHat
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Flat.Localization

open scoped TensorProduct

/-- The base change of the Hurwitz quaternions to ZHat. -/
noncomputable def HurwitzHat : Type := 𝓞 ⊗[ℤ] ZHat

namespace HurwitzHat

/-- The base change of the Hurwitz quaternions to ZHat. -/
scoped notation "𝓞^" => HurwitzHat

noncomputable instance : Ring 𝓞^ := Algebra.TensorProduct.instRing

end HurwitzHat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
noncomputable def HurwitzRat : Type := ℚ ⊗[ℤ] 𝓞

namespace HurwitzRat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
scoped notation "D" => HurwitzRat

noncomputable instance : Ring D := Algebra.TensorProduct.instRing

end HurwitzRat

open scoped HurwitzRat HurwitzHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
noncomputable def HurwitzRatHat : Type := D ⊗[ℤ] ZHat

namespace HurwitzRatHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
scoped notation "D^" => HurwitzRatHat

noncomputable instance : Ring D^ := Algebra.TensorProduct.instRing

/-- The inclusion from D=ℚ+ℚi+ℚj+ℚk to D ⊗ 𝔸, with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₁ : D →ₐ[ℤ] D^ := Algebra.TensorProduct.includeLeft
-- (Algebra.TensorProduct.assoc ℤ ℚ 𝓞 ZHat).symm.trans Algebra.TensorProduct.includeLeft

private instance : IsAddTorsionFree 𝓞 := IsDomain.instIsAddTorsionFreeOfCharZero _

instance : Module.Flat ℤ 𝓞 := by
  rw [IsDedekindDomain.flat_iff_torsion_eq_bot]
  exact Submodule.isTorsionFree_iff_torsion_eq_bot.mp inferInstance

private instance : Module.Flat ℤ ℚ := IsLocalization.flat ℚ (nonZeroDivisors ℤ)

instance : Module.Flat ℤ D := by
  change Module.Flat ℤ (ℚ ⊗[ℤ] 𝓞)
  infer_instance

lemma injective_hRat :
    Function.Injective j₁ := by
  exact Algebra.TensorProduct.includeLeft_injective (Int.cast_injective (α := ZHat))

/-- The inclusion from the profinite Hurwitz quaternions to to 𝔸+𝔸i+𝔸j+𝔸k,
with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₂ : 𝓞^ →ₐ[ℤ] D^ :=
  ((Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm : ℚ ⊗ 𝓞^ ≃ₐ[ℤ] D ⊗ ZHat).toAlgHom.comp
  (Algebra.TensorProduct.includeRight : 𝓞^ →ₐ[ℤ] ℚ ⊗ 𝓞^)

private instance : Module.Flat ℤ 𝓞^ := by
  change Module.Flat ℤ (𝓞 ⊗[ℤ] ZHat)
  infer_instance

lemma injective_zHat :
    Function.Injective j₂ := by
  intro x y hxy
  have := (AlgEquiv.injective
    (Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm) hxy
  exact Algebra.TensorProduct.includeRight_injective (Int.cast_injective (α := ℚ)) this

private noncomputable abbrev assocEquiv :=
  Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat

/-- Any element of ℚ ⊗[ℤ] 𝓞^ can be written as (1/N) ⊗ z'. -/
private lemma rat_tensor_canonicalForm (w : ℚ ⊗[ℤ] 𝓞^) :
    ∃ (N : ℕ+) (z' : 𝓞^), w = (1 / N : ℚ) ⊗ₜ z' := by
  induction w using TensorProduct.induction_on with
  | zero => exact ⟨1, 0, by simp⟩
  | tmul q x =>
    refine ⟨⟨q.den, q.den_pos⟩, q.num • x, ?_⟩
    rw [show (1 / (↑↑⟨q.den, q.den_pos⟩ : ℕ+) : ℚ) = (q.den : ℚ)⁻¹ from by simp [one_div]]
    rw [TensorProduct.tmul_smul, TensorProduct.smul_tmul', zsmul_eq_mul,
      ← Rat.mul_den_eq_num, mul_assoc,
      mul_inv_cancel₀ (Nat.cast_ne_zero.mpr (Rat.den_ne_zero q)), mul_one]
  | add x y hx hy =>
    obtain ⟨N₁, z₁, rfl⟩ := hx
    obtain ⟨N₂, z₂, rfl⟩ := hy
    refine ⟨N₁ * N₂, (N₁ : ℤ) • z₂ + (N₂ : ℤ) • z₁, ?_⟩
    simp only [TensorProduct.tmul_add, ← zsmul_eq_mul,
      TensorProduct.tmul_smul, TensorProduct.smul_tmul']
    simp only [one_div, PNat.mul_coe, Nat.cast_mul, mul_inv_rev, zsmul_eq_mul, Int.cast_natCast,
      ne_eq, Nat.cast_eq_zero, PNat.ne_zero, not_false_eq_true, mul_inv_cancel_left₀]
    rw [add_comm]
    congr
    simp [mul_comm]

private lemma assoc_j₁_j₂ (q : ℚ) (z' : 𝓞^) :
    assocEquiv.symm (q ⊗ₜ[ℤ] z') = j₁ (q ⊗ₜ 1 : D) * j₂ z' := by
  have : q ⊗ₜ[ℤ] z' = (q ⊗ₜ (1 : 𝓞^)) * ((1 : ℚ) ⊗ₜ z') := by
    simp [Algebra.TensorProduct.tmul_mul_tmul]
  rw [this, map_mul]
  rfl

lemma canonicalForm (z : D^) : ∃ (N : ℕ+) (z' : 𝓞^), z = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  obtain ⟨N, z', hw⟩ := rat_tensor_canonicalForm (assocEquiv z)
  refine ⟨N, z', ?_⟩
  have := congr_arg assocEquiv.symm hw
  rw [AlgEquiv.symm_apply_apply] at this
  rw [this, assoc_j₁_j₂]
  congr 2
  simp [one_div]

lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v := sorry

end HurwitzRatHat
